export const projects = [
    {
      _id: "1",
      title: "Mobile App",
      manager: "Mark Burns",
      deadline: "May 25, 2025",
      description: "Develop a cross-platform mobile application for both iOS and Android to enhance user engagement and provide seamless functionality.",
      completion: 78,
      totalHours: 1300,
      completedHours: 1022,
    },
    {
      _id: "2",
      title: "Website Redesign",
      manager: "Sarah Johnson",
      deadline: "June 15, 2025",
      description: "Redesign the company website to improve user experience, modernize the interface, and optimize for mobile devices.",
      completion: 45,
      totalHours: 800,
      completedHours: 360,
    },
    {
      _id: "3",
      title: "Design System",
      manager: "Alex Chen",
      deadline: "July 10, 2025",
      description: "Create a comprehensive design system to ensure consistency across all products and streamline the design and development process.",
      completion: 30,
      totalHours: 600,
      completedHours: 180,
    },
    {
      _id: "4",
      title: "Wireframes",
      manager: "Jessica Lee",
      deadline: "May 30, 2025",
      description: "Develop detailed wireframes for the new product to visualize the layout and structure before moving to the design phase.",
      completion: 90,
      totalHours: 400,
      completedHours: 360,
    },
    {
      _id: "5",
      title: "Software App",
      manager: "Michael Brown",
      deadline: "August 5, 2025",
      description: "Build a robust software application to automate business processes and improve operational efficiency.",
      completion: 15,
      totalHours: 1500,
      completedHours: 225,
    },
  ];