export const projects = [
    {
      id: "1",
      name: "Mobile App",
      manager: "Mark Burns",
      dueDate: "May 25, 2025",
      description: "Develop a cross-platform mobile application for both iOS and Android to enhance user engagement and provide seamless functionality.",
      progress: 78,
      totalHours: 1300,
      completedHours: 1022,
    },
    {
      id: "2",
      name: "Website Redesign",
      manager: "Sarah Johnson",
      dueDate: "June 15, 2025",
      description: "Redesign the company website to improve user experience, modernize the interface, and optimize for mobile devices.",
      progress: 45,
      totalHours: 800,
      completedHours: 360,
    },
    {
      id: "3",
      name: "Design System",
      manager: "Alex Chen",
      dueDate: "July 10, 2025",
      description: "Create a comprehensive design system to ensure consistency across all products and streamline the design and development process.",
      progress: 30,
      totalHours: 600,
      completedHours: 180,
    },
    {
      id: "4",
      name: "Wireframes",
      manager: "Jessica Lee",
      dueDate: "May 30, 2025",
      description: "Develop detailed wireframes for the new product to visualize the layout and structure before moving to the design phase.",
      progress: 90,
      totalHours: 400,
      completedHours: 360,
    },
    {
      id: "5",
      name: "Software App",
      manager: "Michael Brown",
      dueDate: "August 5, 2025",
      description: "Build a robust software application to automate business processes and improve operational efficiency.",
      progress: 15,
      totalHours: 1500,
      completedHours: 225,
    },
  ];