export const users = [
    {
      id: "1",
      name: "Victor Zedomi",
      email: "victor@example.com",
      role: "Designer",
      avatar: "",
      initials: "VZ",
    },
    {
      id: "2",
      name: "Mark Burns",
      email: "mark@example.com",
      role: "Product Manager",
      avatar: "",
      initials: "MB",
    },
    {
      id: "3",
      name: "Pete Johnson",
      email: "pete@example.com",
      role: "Engineering",
      avatar: "",
      initials: "PJ",
    },
    {
      id: "4",
      name: "Eamonn Kelly",
      email: "eamonn@example.com",
      role: "Engineering",
      avatar: "",
      initials: "EK",
    },
    {
      id: "5",
      name: "Ronan Smith",
      email: "ronan@example.com",
      role: "Product",
      avatar: "",
      initials: "RS",
    },
    {
      id: "6",
      name: "Sarah Johnson",
      email: "sarah@example.com",
      role: "Designer",
      avatar: "",
      initials: "SJ",
    },
    {
      id: "7",
      name: "Alex Chen",
      email: "alex@example.com",
      role: "Engineering",
      avatar: "",
      initials: "AC",
    },
  ]